### ISSUE TITLE
HellGateMonitor v1.0.0 TODO

### ISSUE THREAD

**Issue by Hotakus** [Hotakus/HellGateMonitor#3]
# TODO：

- [ ] 添加：简易投屏功能
- [ ] 优化：硬件信息监控功能
- [x] 重构：setup框架
- [x] 优化：天气组件
- [x] 优化：调整硬件请求对象的生存周期（优先）
- [x] 优化：优化现有框架（优先）
- [x] 优化：蓝牙框架
- [x] 优化：LVGL界面设计
- [x] 重构：设计MVC模式
- [x] 添加：天气图标
- [x] 测试：天气图标方案
- [x] 优化：天气解析
- [x] 添加：Debug开关
- [x] 优化：天气功能
- [x] 优化：取消初始化时的创建任务行为
- [x] 测试：屏幕显示效果
- [x] 优化：网络时间功能
- [x] 添加：硬件信息获取功能
- [x] 优化：B站功能
- [x] 添加：简单的MC风格时钟
- [x] 优化：页面功能划分

---
# 详细TODO

## 🖥硬件监控功能TODO

欲添加LVGL硬件监控对象，包含硬件数据对象和UI对象：
- UI对象控制UI行为，例如UI的进场与退场，及前台数据更新等；
- 硬件数据对象存放UI位置信息、硬件类型与其监控数据  

LVGL硬件监控对象固定为4，UI位置分别为左上、左下、右上、右下，通过绑定不同的UI对象与不同的硬件数据对象，实现硬件监控UI的更替与数据的更替

- [x] 创建 “LVGL硬件监控对象”
- [x] 创建 “UI对象”
- [x] 添加UI动效
- [x] 设计硬件监控界面
- [x] 创建 “硬件数据对象”

## ☀天气功能TODO

- [x] 完善天气JSON解析
- [x] 添加UI动效
- [x] 完善 天气位置信息存储与读取
- [x] 设计并添加天气图标

## 📺B站功能TODO

- [x] 添加UI动效
- [x] 设计UI
- [x] 实现B站各种数据获取与存储

## 🎥简易投屏功能TODO
- [ ] 添加动效
- [ ] 按[HgmTCP](https://github.com/Hotakus/HellGateMonitor/blob/master/Source/HgmApp/HgmWiFi/HgmTCP/README.md)格式实现投屏数据帧接收

## 🇨🇳 部分中文支持
因存储空间限制，无法添加太多中文字体，所以采用以下方案，并限制中文字体个数
- [x] 若检测到中文，则使用中文字体，否则使用默认英文字体，主要供给向“B站功能”的用户名称显示，B站中文名则有可能显示为空（因为中文字体个数限制）

**Comment by Hotakus** [comment]
欲添加LVGL硬件监控对象，包含硬件数据对象和UI对象：
- UI对象控制UI行为，例如UI的进场与退场，及前台数据更新等；
- 硬件数据对象存放UI位置信息、硬件类型与其监控数据  

LVGL硬件监控对象固定为4，UI位置分别为左上、左下、右上、右下，通过绑定不同的UI对象与不同的硬件数据对象，实现硬件监控UI的更替与数据的更替

- [ ] 创建 “LVGL硬件监控对象”
- [ ] 创建 “UI对象”
- [ ] 创建 “硬件数据对象”

**Comment by Hotakus** [comment]
## 重写WiFi和蓝牙的实现框架

- [ ] 完成
